#!/bin/bash

# apply-theme.sh — Regenerate all theme files from palette.conf
# Usage: ./apply-theme.sh [--palette /path/to/palette.conf]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PALETTE="${1:-$SCRIPT_DIR/palette.conf}"
if [ "$1" = "--palette" ]; then PALETTE="$2"; fi

if [ ! -f "$PALETTE" ]; then
    echo "palette.conf not found: $PALETTE"
    exit 1
fi

# shellcheck source=/dev/null
source "$PALETTE"

GREEN='\033[0;32m'
BLUE_C='\033[0;34m'
NC='\033[0m'
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
info() { echo -e "${BLUE_C}[→]${NC} $1"; }

# Strip leading # from hex for formats that need it
hex() { echo "${1#\#}"; }

# Convert #rrggbb to "r, g, b" decimal (terminator profile format)
rgb() {
    local h="${1#\#}"
    printf "%d, %d, %d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

info "Palette: $PALETTE"
info "Generating theme files..."
echo ""

# ============================================================
# Ghostty theme
# ============================================================
GHOSTTY_THEME="$SCRIPT_DIR/ghostty/themes/manga-mono"
mkdir -p "$(dirname "$GHOSTTY_THEME")"
cat > "$GHOSTTY_THEME" << EOF
# Manga Mono — Ghostty Theme
# Generated by apply-theme.sh — edit palette.conf to change colors.

# --- normal ---
palette = 0=$ANSI_0
palette = 1=$ANSI_1
palette = 2=$ANSI_2
palette = 3=$ANSI_3
palette = 4=$ANSI_4
palette = 5=$ANSI_5
palette = 6=$ANSI_6
palette = 7=$ANSI_7

# --- bright ---
palette = 8=$ANSI_8
palette = 9=$ANSI_9
palette = 10=$ANSI_10
palette = 11=$ANSI_11
palette = 12=$ANSI_12
palette = 13=$ANSI_13
palette = 14=$ANSI_14
palette = 15=$ANSI_15

# --- core ---
background = $CANVAS
foreground = $TEXT

# --- cursor ---
cursor-color = $BLUE
cursor-text = $CANVAS

# --- selection ---
selection-background = $RAISED
selection-foreground = $TEXT
EOF
ok "ghostty/themes/manga-mono"

# ============================================================
# btop theme
# ============================================================
BTOP_THEME="$SCRIPT_DIR/btop/themes/manga-mono.theme"
mkdir -p "$(dirname "$BTOP_THEME")"
cat > "$BTOP_THEME" << EOF
# Manga Mono — btop theme
# Generated by apply-theme.sh — edit palette.conf to change colors.

theme[main_bg]="$CANVAS"
theme[main_fg]="$TEXT"
theme[title]="$TEXT"
theme[hi_fg]="$BLUE"
theme[selected_bg]="$BLUE_MID"
theme[selected_fg]="$TEXT"
theme[inactive_fg]="$DARK_RAISED"
theme[graph_text]="$SOFT"
theme[meter_bg]="$RAISED"
theme[proc_misc]="$TONE"

theme[cpu_box]="$BLUE"
theme[mem_box]="$TONE"
theme[net_box]="$LINE"
theme[proc_box]="$BLUE"

theme[temp_start]="$TONE"
theme[temp_mid]="$BLUE"
theme[temp_end]="$BLUE_BRIGHT"

theme[cpu_start]="$RAISED"
theme[cpu_mid]="$BLUE_MID"
theme[cpu_end]="$BLUE"

theme[free_start]="$RAISED"
theme[free_mid]="$LINE"
theme[free_end]="$DARK_RAISED"

theme[cached_start]="$RAISED"
theme[cached_mid]="#2d3a4a"
theme[cached_end]="$BLUE_MID"

theme[available_start]="$CANVAS"
theme[available_mid]="#1c2e3a"
theme[available_end]="$BLUE"

theme[used_start]="$RAISED"
theme[used_mid]="#2d3a5a"
theme[used_end]="$BLUE"

theme[download_start]="$RAISED"
theme[download_mid]="$BLUE_MID"
theme[download_end]="$BLUE"

theme[upload_start]="$RAISED"
theme[upload_mid]="$LINE"
theme[upload_end]="$TONE"

theme[process_start]="$RAISED"
theme[process_mid]="$BLUE_MID"
theme[process_end]="$BLUE"
EOF
ok "btop/themes/manga-mono.theme"

# ============================================================
# cava config
# ============================================================
CAVA_CONF="$SCRIPT_DIR/cava/config"
mkdir -p "$(dirname "$CAVA_CONF")"
cat > "$CAVA_CONF" << EOF
[color]
gradient = 1
gradient_count = 6
gradient_color_1 = '$RAISED'
gradient_color_2 = '#2d3a4a'
gradient_color_3 = '$BLUE_MID'
gradient_color_4 = '$BLUE'
gradient_color_5 = '$BLUE_BRIGHT'
gradient_color_6 = '$BLUE_LIGHT'
EOF
ok "cava/config"

# ============================================================
# GTK 3 theme
# ============================================================
GTK_CSS="$SCRIPT_DIR/gtk/gtk-3.0/gtk.css"
mkdir -p "$(dirname "$GTK_CSS")"
cat > "$GTK_CSS" << EOF
/* Manga Mono — GTK3 Theme
   Generated by apply-theme.sh — edit palette.conf to change colors.
   Colors only. Default Adwaita shapes/styles.
*/

@define-color theme_bg_color $CANVAS;
@define-color theme_fg_color $TEXT;
@define-color theme_base_color $SURFACE;
@define-color theme_text_color $TEXT;
@define-color theme_selected_bg_color $BLUE;
@define-color theme_selected_fg_color $CANVAS;
@define-color theme_tooltip_bg_color $RAISED;
@define-color theme_tooltip_fg_color $TEXT;
@define-color insensitive_bg_color $SURFACE;
@define-color insensitive_fg_color $DARK_RAISED;
@define-color insensitive_base_color $CANVAS;
@define-color theme_unfocused_bg_color $CANVAS;
@define-color theme_unfocused_fg_color $TONE;
@define-color borders $LINE;
@define-color unfocused_borders $RAISED;
@define-color warning_color $ANSI_3;
@define-color error_color $BRICK;
@define-color success_color $ANSI_2;
@define-color accent_color $BLUE;
@define-color accent_bg_color $BLUE;
@define-color accent_fg_color $CANVAS;
@define-color destructive_color $BRICK;
@define-color destructive_bg_color $BRICK;

window, .background {
  background-color: @theme_bg_color;
  color: @theme_fg_color;
}

/* Terminator splitter — transparent, 1px only */
paned > separator {
  background-color: alpha($BLUE, 0.15);
  min-width: 1px;
  min-height: 1px;
  padding: 0;
}

headerbar, .titlebar {
  background-color: $RAISED;
  color: @theme_fg_color;
  border-bottom: 1px solid @borders;
  min-height: 18px;
  padding: 0 6px;
}

headerbar * { margin-top: 0; margin-bottom: 0; }
headerbar .title { font-size: 13px; }

headerbar:backdrop, .titlebar:backdrop {
  background-color: $SURFACE;
  color: @theme_unfocused_fg_color;
}

tooltip {
  background-color: @theme_tooltip_bg_color;
  color: @theme_tooltip_fg_color;
  border: 1px solid @borders;
}

selection, *:selected {
  background-color: alpha(@theme_selected_bg_color, 0.25);
  color: @theme_fg_color;
}
EOF
ok "gtk/gtk-3.0/gtk.css"

# ============================================================
# Neovim (mini.base16)
# ============================================================
NVIM_LUA="$SCRIPT_DIR/nvim/lua/plugins/manga-mono.lua"
mkdir -p "$(dirname "$NVIM_LUA")"
cat > "$NVIM_LUA" << EOF
return {
  "echasnovski/mini.base16",
  version = false,
  priority = 1000,
  config = function()
    require("mini.base16").setup({
      palette = {
        base00 = "$CANVAS",        -- background
        base01 = "$SURFACE",       -- surface / cursorline
        base02 = "$RAISED",        -- selection / raised
        base03 = "$TONE",          -- comments
        base04 = "$ANSI_3",        -- inactive fg / line numbers
        base05 = "$TEXT",          -- default fg
        base06 = "$SOFT",          -- light fg
        base07 = "$ANSI_15",       -- bright white
        base08 = "$BRICK",         -- constants, numbers, errors
        base09 = "$BRICK_BRIGHT",  -- bold errors
        base0A = "$ANSI_3",        -- types, classes
        base0B = "$ANSI_10",       -- strings
        base0C = "$BLUE_LIGHT",    -- regex, special strings
        base0D = "$BLUE",          -- functions, links
        base0E = "$BLUE_BRIGHT",   -- keywords
        base0F = "$BRICK",         -- deprecated/embedded
      },
      use_cterm = true,
    })

    -- Transparent background (match terminal)
    vim.api.nvim_set_hl(0, "Normal",      { bg = "none" })
    vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
    vim.api.nvim_set_hl(0, "NormalNC",    { bg = "none" })
    vim.api.nvim_set_hl(0, "SignColumn",  { bg = "none" })
    vim.api.nvim_set_hl(0, "LineNr",      { bg = "none" })
  end,
}
EOF
ok "nvim/lua/plugins/manga-mono.lua"

# ============================================================
# Starship palette blocks (append/replace in starship.toml)
# ============================================================
STARSHIP="$SCRIPT_DIR/starship.toml"
if [ -f "$STARSHIP" ]; then
    # Strip existing manga-mono palette blocks from the end
    perl -i -0pe 's/\n+# ── Manga Mono.*//s' "$STARSHIP"

    cat >> "$STARSHIP" << EOF

# ── Manga Mono — light paper blocks on dark terminal (recommended) ──
[palettes.manga-mono-light]
purple  = "$LIGHT_RAISED"
cyan    = "$BLUE_SEL"
pink    = "$LIGHT_LINE"
green   = "$LIGHT_SURFACE"
comment = "$LIGHT_CANVAS"
blue    = "$BLUE"
yellow  = "$BLUE"
red     = "$BRICK_BRIGHT"
crust   = "$LIGHT_TEXT"
base    = "$CANVAS"
mantle  = "$SURFACE"

# ── Manga Mono — dark grey blocks on light terminal ──
[palettes.manga-mono-dark]
purple  = "$RAISED"
cyan    = "$BLUE"
pink    = "$LINE"
green   = "$SURFACE"
comment = "$SURFACE"
blue    = "$BLUE"
yellow  = "$BLUE"
red     = "$BRICK"
crust   = "$TEXT"
base    = "$CANVAS"
mantle  = "$SURFACE"
EOF
    ok "starship.toml (palette blocks)"
else
    echo "  [skip] starship.toml not found"
fi

# ============================================================
# Terminator theme profile
# ============================================================
TERM_THEME="$SCRIPT_DIR/terminator/manga-mono"
PALETTE_HEX="${ANSI_0}:${ANSI_1}:${ANSI_2}:${ANSI_3}:${ANSI_4}:${ANSI_5}:${ANSI_6}:${ANSI_7}:${ANSI_8}:${ANSI_9}:${ANSI_10}:${ANSI_11}:${ANSI_12}:${ANSI_13}:${ANSI_14}:${ANSI_15}"
mkdir -p "$(dirname "$TERM_THEME")"
cat > "$TERM_THEME" << EOF
[global_config]
  focus = True
  title_hide_sdist = True
  broadcast_tab = True

[keybindings]
  zoom_in = Ctrl+plus
  zoom_out = Ctrl+minus

[profiles]
  [[manga-mono]]
    use_system_font = False
    font = $FONT_FAMILY $FONT_SIZE
    allow_bold = True
    cursor_shape = BLOCK
    cursor_foreground_color = "$(rgb "$CANVAS")"
    cursor_color = "$(rgb "$BLUE")"
    foreground_color = "$(rgb "$TEXT")"
    background_color = "$(rgb "$CANVAS")"
    highlight_background_color = "$(rgb "$RAISED")"
    highlight_foreground_color = "$(rgb "$TEXT")"
    bold_colors_same_as_fg = False
    scrollback_lines = 5000
    palette = "$PALETTE_HEX"
    background_mode = dark
EOF
ok "terminator/manga-mono"

# ============================================================
# Terminator config (full)
# ============================================================
TERM_CONF="$SCRIPT_DIR/terminator/config"
BG_IMG="${WALLPAPER_PATH:-$(realpath "$SCRIPT_DIR/assets/wallpaperflare.jpeg" 2>/dev/null || echo "")}"
cat > "$TERM_CONF" << EOF
[global_config]
  focus = True
  title_transmit_fg_color = "$TEXT"
  title_transmit_bg_color = "$BLUE_MID"
  title_receive_fg_color = "$SOFT"
  title_receive_bg_color = "#1c2e3a"
  title_inactive_fg_color = "$DARK_RAISED"
  title_inactive_bg_color = "$SURFACE"
  title_use_system_font = False
  title_font = $FONT_FAMILY 9
[keybindings]
  zoom_in = Ctrl+plus
  zoom_out = Ctrl+minus
[profiles]
  [[default]]
    background_color = "$CANVAS"
    background_darkness = 0.96
    background_type = image
    cursor_shape = BLOCK
    cursor_color = "$BLUE"
    font = $FONT_FAMILY $FONT_SIZE
    foreground_color = "$TEXT"
    palette = "$PALETTE_HEX"
    use_system_font = False
    background_image = $BG_IMG
  [[manga-mono]]
    background_color = "$CANVAS"
    background_darkness = 0.96
    background_type = image
    cursor_shape = BLOCK
    cursor_color = "$BLUE"
    font = $FONT_FAMILY $FONT_SIZE
    foreground_color = "$TEXT"
    palette = "$PALETTE_HEX"
    use_system_font = False
    background_image = $BG_IMG
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
      maximised = True
      fullscreen = False
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = manga-mono
[plugins]
EOF
ok "terminator/config"

echo ""
echo "All theme files regenerated from: $PALETTE"
echo "To apply: restart your apps or reload their configs."
